# -*- coding: utf-8 -*-
# ! /usr/bin/env python

"""
@author:LiWei
@license:LiWei
@contact:877129310@qq.com
@version:
@var:
@note:

"""
import requests
from uuid import uuid4
import random
import json
import time

spider_names = [{"spider_name": "thx"}, {"spider_name": "jjszbgs"}, {"spider_name": "jjxw"}, {"spider_name": "0792ju"},
                {"spider_name": "dzwww"}, {"spider_name": "ahjjw"}, {"spider_name": "rx365"},
                {"spider_name": "people1"},
                {"spider_name": "china_wannian"}, {"spider_name": "people2"}, {"spider_name": "people3"},
                {"spider_name": "laian"},
                {"spider_name": "jxntv"}, {"spider_name": "ts_xx"}, {"spider_name": "chinafood368"},
                {"spider_name": "zhanho"},
                {"spider_name": "jxntv2"}, {"spider_name": "suqionghuag"}, {"spider_name": "px_jxnews"},
                {"spider_name": "ybxww"},
                {"spider_name": "jxnews2"}, {"spider_name": "ga_jwshq"}, {"spider_name": "people"},
                {"spider_name": "bbaqw"},
                {"spider_name": "qingdaonews"}, {"spider_name": "bandao"}, {"spider_name": "cqaoxue"},
                {"spider_name": "qingdaonews2"}, {"spider_name": "qingdaonews1"}, {"spider_name": "shandongfood"},
                {"spider_name": "ndidu"}, {"spider_name": "aliidea"}, {"spider_name": "ylqss"},
                {"spider_name": "ybxww2"},
                {"spider_name": "chuzhou"}, {"spider_name": "mytianchang"}, {"spider_name": "ahhy"},
                {"spider_name": "cnscnet"},
                {"spider_name": "sohu"}, {"spider_name": "bjradio"}, {"spider_name": "cxxwnews"},
                {"spider_name": "yugan"},
                {"spider_name": "zwfz"}, {"spider_name": "chinawuyuan"}, {"spider_name": "gov"},
                {"spider_name": "srxww"},
                {"spider_name": "jxsr_jxnews"}, {"spider_name": "sz"}, {"spider_name": "wz_jxnews"},
                {"spider_name": "sz1"},
                {"spider_name": "wz_jxnews2"}, {"spider_name": "vojs"}, {"spider_name": "jsbc"},
                {"spider_name": "zgdx_gov"},
                {"spider_name": "chinafx_gov"}, {"spider_name": "china_wannian_gov"}, {"spider_name": "hedian_bjx"},
                {"spider_name": "stock_caijing"}, {"spider_name": "bjx"}, {"spider_name": "js_chinaso"},
                {"spider_name": "jsdushi"}, {"spider_name": "yx_cnyixing"}, {"spider_name": "jxntv3"},
                {"spider_name": "yx_cnyixing1"}, {"spider_name": "jdzol"}, {"spider_name": "jdz_news"},
                {"spider_name": "wx"},
                {"spider_name": "jxjdz_jxnews"}, {"spider_name": "thmz"}, {"spider_name": "tdcm"},
                {"spider_name": "jxscnews"},
                {"spider_name": "gd_qq"}, {"spider_name": "jnwb_net"}, {"spider_name": "cqc"},
                {"spider_name": "focus_tianya"},
                {"spider_name": "samr_aqsiq_gov"}, {"spider_name": "southcn"}, {"spider_name": "sgsgroup"},
                {"spider_name": "ycwb"}, {"spider_name": "tuv_sud"}, {"spider_name": "cqn"}, {"spider_name": "dayoo"},
                {"spider_name": "deban56"}, {"spider_name": "grad_sdu_edu"}, {"spider_name": "deban57"},
                {"spider_name": "ahaq_wenming"}, {"spider_name": "deban58"}, {"spider_name": "thnews_gov"},
                {"spider_name": "th_aqzy_gov"}, {"spider_name": "qyzc_net"}, {"spider_name": "aqzy_gov"},
                {"spider_name": "pusa123"}, {"spider_name": "thx_gov"}, {"spider_name": "pusa125"},
                {"spider_name": "news_sipac_gov"}, {"spider_name": "fuyang"}, {"spider_name": "suda_edu"},
                {"spider_name": "jschina"}, {"spider_name": "fuyang53"}, {"spider_name": "news_snd_gov"},
                {"spider_name": "mygd_qq_1"}, {"spider_name": "ai2l_net"}, {"spider_name": "test4exam"},
                {"spider_name": "gztv"},
                {"spider_name": "news_cn"}, {"spider_name": "southcn2"}, {"spider_name": "pinlue"},
                {"spider_name": "suzhou_gov"},
                {"spider_name": "ycwb2"}, {"spider_name": "am1115"}, {"spider_name": "dayoo2"},
                {"spider_name": "news_csxww"},
                {"spider_name": "gz_bendibao"}, {"spider_name": "suzhounew"}, {"spider_name": "iecity"},
                {"spider_name": "gd_sina"}, {"spider_name": "szdushi"}, {"spider_name": "guangzhouf"},
                {"spider_name": "money_2500sz"}, {"spider_name": "news_2507sz"}, {"spider_name": "subaonet"},
                {"spider_name": "gznews_gov"}, {"spider_name": "longhoo_net"}, {"spider_name": "dayoo1"},
                {"spider_name": "legal_qianlong"}, {"spider_name": "gdzj_wenming"}, {"spider_name": "pdsxww"},
                {"spider_name": "pdsxww1"}, {"spider_name": "ayrbs"}, {"spider_name": "southcn3"},
                {"spider_name": "ayrbs1"},
                {"spider_name": "southcn4"}, {"spider_name": "southcn5"}, {"spider_name": "en_zjna_gov"},
                {"spider_name": "en_zjna_gov1"}, {"spider_name": "swcszx"}, {"spider_name": "sq1996"},
                {"spider_name": "sq1997"},
                {"spider_name": "wmdw_jswmw"}, {"spider_name": "sq1998"}, {"spider_name": "sq1999"},
                {"spider_name": "sq2000"},
                {"spider_name": "js_people"}, {"spider_name": "xuyi_tv"}, {"spider_name": "msh_jschina_js"},
                {"spider_name": "msh_jschina_nj"}, {"spider_name": "msh_jschina_tz"}, {"spider_name": "msh_jschina_zj"},
                {"spider_name": "msh_jschina_yz"}, {"spider_name": "msh_jschina_yc"}, {"spider_name": "msh_jschina_ha"},
                {"spider_name": "msh_jschina_lyg"}, {"spider_name": "msh_jschina_nt"},
                {"spider_name": "msh_jschina_sz"},
                {"spider_name": "msh_jschina_cz"}, {"spider_name": "js_people2"}, {"spider_name": "msh_jschina_xz"},
                {"spider_name": "msh_jschina_wx"}, {"spider_name": "msh_jschina_sq"}, {"spider_name": "msh_jschina"},
                {"spider_name": "jxntv4"}, {"spider_name": "ju"}, {"spider_name": "jxntv5"}, {"spider_name": "guixitv"},
                {"spider_name": "yt105"}, {"spider_name": "jxntv6"}, {"spider_name": "ncnews"},
                {"spider_name": "jxdtzy"},
                {"spider_name": "jxntv1"}, {"spider_name": "jj_jxnews"}, {"spider_name": "yichunwang079568"},
                {"spider_name": "jjxw2"}, {"spider_name": "jxxy_jxnews"}, {"spider_name": "jxntv_xy"},
                {"spider_name": "kyjlb_rmjtxw"}, {"spider_name": "hnzs_rmjtxw"}, {"spider_name": "scjt_rmjtxw"},
                {"spider_name": "jxsc_rmjtxw"}, {"spider_name": "hebjt_rmjtxw"}, {"spider_name": "shms_rmjtxw"},
                {"spider_name": "nmjt_rmjtxw"}, {"spider_name": "fzjt_rmjtxw"}, {"spider_name": "srsc_rmjtxw"},
                {"spider_name": "glgc_rmjtxw"}, {"spider_name": "sxjt_rmjtxw"}, {"spider_name": "hnjt_rmjtxw"},
                {"spider_name": "hbjt_rmjtxw"}, {"spider_name": "rmjtxw_news"}, {"spider_name": "huanqiu"},
                {"spider_name": "huanqiu1"}, {"spider_name": "thepaper"}, {"spider_name": "qstheory"},
                {"spider_name": "toutiao_sogou"}, {"spider_name": "news_tom"}, {"spider_name": "news_cctv"},
                {"spider_name": "shipin_gmw"}, {"spider_name": "travel_gmw"}, {"spider_name": "news_cnr"},
                {"spider_name": "news_cnr1"}, {"spider_name": "news_cnr2"}, {"spider_name": "difang_gmw"},
                {"spider_name": "js_qq"}, {"spider_name": "difang_gmw2"}, {"spider_name": "news_baidu"},
                {"spider_name": "news_china"}, {"spider_name": "difang_gmw3"}, {"spider_name": "toutiao_china"},
                {"spider_name": "difang_gmw4"}, {"spider_name": "difang_gmw5"}, {"spider_name": "cpc_people"},
                {"spider_name": "difang_gmw6"}, {"spider_name": "difang_gmw7"}, {"spider_name": "difang_gmw8"},
                {"spider_name": "chinawuyuan1"}, {"spider_name": "difang_gmw9"}, {"spider_name": "difang_gmw10"},
                {"spider_name": "dqccc"}, {"spider_name": "difang_gmw11"}, {"spider_name": "difang_gmw12"},
                {"spider_name": "difang_gmw13"}, {"spider_name": "difang_gmw14"}, {"spider_name": "jxnews"},
                {"spider_name": "difang_gmw15"}, {"spider_name": "difang_gmw16"}, {"spider_name": "difang_gmw17"},
                {"spider_name": "difang_gmw18"}, {"spider_name": "jx.people"}, {"spider_name": "difang_gmw19"},
                {"spider_name": "difang_gmw20"}, {"spider_name": "jx_people_nc"}, {"spider_name": "difang_gmw21"},
                {"spider_name": "difang_gmw22"}, {"spider_name": "jx_people_jj"}, {"spider_name": "difang_gmw23"},
                {"spider_name": "difang_gmw24"}, {"spider_name": "difang_gmw25"}, {"spider_name": "difang_gmw26"},
                {"spider_name": "jx_people_px"}, {"spider_name": "difang_gmw27"}, {"spider_name": "difang_gmw28"},
                {"spider_name": "jx_people_xy"}, {"spider_name": "difang_gmw29"}, {"spider_name": "difang_gmw30"},
                {"spider_name": "difang_gmw31"}, {"spider_name": "jx_people_gz"}, {"spider_name": "difang_gmw32"},
                {"spider_name": "difang_gmw33"}, {"spider_name": "difang_gmw34"}, {"spider_name": "jx_people_yc"},
                {"spider_name": "zjjt_rmjtxw"}, {"spider_name": "jx_people_sr"}, {"spider_name": "jx_people_ja"},
                {"spider_name": "jx_people_fz"}, {"spider_name": "jx_people_yh"}, {"spider_name": "rmjtxw"},
                {"spider_name": "jx_people_fc"}, {"spider_name": "jx_people_nk"}, {"spider_name": "jx_people_jdz"},
                {"spider_name": "jx_people_qsh"}, {"spider_name": "society_sohu"}, {"spider_name": "politics_gmw"},
                {"spider_name": "gd_people"}, {"spider_name": "news_sohu"}, {"spider_name": "sd_people"},
                {"spider_name": "business_sohu"}, {"spider_name": "gz_bendibao1"}, {"spider_name": "qq"},
                {"spider_name": "economy_gmw"}, {"spider_name": "xinhuanet"}, {"spider_name": "news"},
                {"spider_name": "life_gmw"},
                {"spider_name": "news_163"}, {"spider_name": "sd_xinhuanet"}, {"spider_name": "caixin"},
                {"spider_name": "btime"},
                {"spider_name": "legal_gmw"}, {"spider_name": "health_gmw"}, {"spider_name": "js_xinhuanet"},
                {"spider_name": "srxww2"}, {"spider_name": "bj_chinadaily"}, {"spider_name": "yinhang123"},
                {"spider_name": "sd_sina"}, {"spider_name": "ynet"}, {"spider_name": "jiangsu_sina"},
                {"spider_name": "tj_chinadaily"}, {"spider_name": "people_fz"}, {"spider_name": "heb_chinadaily"},
                {"spider_name": "ah_sina"}, {"spider_name": "news_sina"}, {"spider_name": "legaldaily"},
                {"spider_name": "sx_chinadaily"}, {"spider_name": "jx_sina"}, {"spider_name": "ln_chinadaily"},
                {"spider_name": "legaldaily1"}, {"spider_name": "gd_sina2"}, {"spider_name": "jl_chinadaily"},
                {"spider_name": "hlj_chinadaily"}, {"spider_name": "sh_chinadaily"}, {"spider_name": "js_chinadaily"},
                {"spider_name": "zj_chinadaily"}, {"spider_name": "anhui163"}, {"spider_name": "nncc626"},
                {"spider_name": "fj_chinadaily"}, {"spider_name": "cxnews_cnnb"}, {"spider_name": "jx_chinadaily"},
                {"spider_name": "sd_chinadaily"}, {"spider_name": "hen_chinadaily"}, {"spider_name": "hb_chinadaily"},
                {"spider_name": "hn_chinadaily"}, {"spider_name": "gd_chinadaily"}, {"spider_name": "gx_chinadaily"},
                {"spider_name": "finance_ifeng"}, {"spider_name": "news_eastday"}, {"spider_name": "news_ifeng"},
                {"spider_name": "hain_chinadaily"}, {"spider_name": "ah_ifeng"}, {"spider_name": "cq_chinadaily"},
                {"spider_name": "sc_chinadaily"}, {"spider_name": "yn_chinadaily"}, {"spider_name": "ah_ifeng_liuan"},
                {"spider_name": "gz_chinadaily"}, {"spider_name": "ah_ifeng_suzhou"},
                {"spider_name": "ah_ifeng_huaibei"},
                {"spider_name": "jn720"}, {"spider_name": "xz_chinadaily"}, {"spider_name": "shx_chinadaily"},
                {"spider_name": "xiaoqiweb"}, {"spider_name": "xj_chinadaily"}, {"spider_name": "sz_chinadaily"},
                {"spider_name": "qiye_chinadaily"}, {"spider_name": "news_jnnc"}, {"spider_name": "tech_chinadaily"},
                {"spider_name": "world_chinadaily"}, {"spider_name": "wallstreetcn"}, {"spider_name": "cn_chinadaily"},
                {"spider_name": "news_qq"}, {"spider_name": "js_ifeng_nj"}, {"spider_name": "js_ifeng_zj"},
                {"spider_name": "js_ifeng_yz"}, {"spider_name": "js_ifeng_tz"}, {"spider_name": "js_ifeng_sq"},
                {"spider_name": "banyuetan"}, {"spider_name": "js_ifeng_ha"}, {"spider_name": "js_ifeng_lyg"},
                {"spider_name": "sd_ifeng"}, {"spider_name": "jx_ifeng_nc"}, {"spider_name": "jx_ifeng_gz"},
                {"spider_name": "jx_ifeng_jj"}, {"spider_name": "jx_ifeng_sr"}, {"spider_name": "jx_ifeng_px"},
                {"spider_name": "jx_ifeng_fz"}, {"spider_name": "jx_ifeng_ja"}, {"spider_name": "jx_ifeng_xy"},
                {"spider_name": "aq.ycwb"}, {"spider_name": "jx_ifeng_yc"}, {"spider_name": "jx_ifeng_yt"},
                {"spider_name": "jx_ifeng_sc"}, {"spider_name": "jx_ifeng_yh"}, {"spider_name": "ah_ifeng_chizhou"},
                {"spider_name": "ah_ifeng_xuanchen"}, {"spider_name": "jx_ifeng_yd"}, {"spider_name": "jx_ifeng_ay"},
                {"spider_name": "jx_ifeng_jdz"}, {"spider_name": "jx_ifeng_hgt"}, {"spider_name": "ah_ifeng_huangshan"},
                {"spider_name": "ah_ifeng_tonglin"}, {"spider_name": "ah_ifeng_huainan"}, {"spider_name": "news_ycwb"},
                {"spider_name": "ah_ifeng_anqing"}, {"spider_name": "wangyi_164"}, {"spider_name": "ah_ifeng_bengbu"},
                {"spider_name": "3c_ycwb"}, {"spider_name": "ah_ifeng_bozhou"}, {"spider_name": "ah_ifeng_chuzhou"},
                {"spider_name": "ah_ifeng_fuyang"}, {"spider_name": "ah_ifeng_wuhu"}, {"spider_name": "ah_ifeng_hefei"},
                {"spider_name": "money_ycwb"}, {"spider_name": "chinanews"}, {"spider_name": "blog_qq"},
                {"spider_name": "iqilu"},
                {"spider_name": "edu_ycwb"}, {"spider_name": "yuqing_ycwb"}, {"spider_name": "qdxin"},
                {"spider_name": "qprs_net"},
                {"spider_name": "chinanews2"}, {"spider_name": "sp_ycwb"}, {"spider_name": "qidongnews"},
                {"spider_name": "chinanews3"}, {"spider_name": "qlwb"}, {"spider_name": "qlwb1"},
                {"spider_name": "infzm"},
                {"spider_name": "qlwb2"}, {"spider_name": "news_ycwb1"}, {"spider_name": "qlwb_shangdong"},
                {"spider_name": "ln_cri"}, {"spider_name": "qlwb_jinan"}, {"spider_name": "jrwh_qlwb"},
                {"spider_name": "yantai_qlwb"}, {"spider_name": "ycwb1"}, {"spider_name": "hn_cri"},
                {"spider_name": "jrwf_qlwb"},
                {"spider_name": "hb_cri"}, {"spider_name": "binzhou_qlwb"}, {"spider_name": "linyi_qlwb"},
                {"spider_name": "taian_qlwb"}, {"spider_name": "jl_cri"}, {"spider_name": "gx_cri"},
                {"spider_name": "gz_cri"},
                {"spider_name": "wfnews"}, {"spider_name": "mini_eastday"}, {"spider_name": "tech_163"},
                {"spider_name": "tech_164"}, {"spider_name": "kandian_youth"}, {"spider_name": "money_163"},
                {"spider_name": "finance_youth"}, {"spider_name": "money_164"}, {"spider_name": "money_165"},
                {"spider_name": "gz_cri2"}, {"spider_name": "sx_cri"}, {"spider_name": "money_166"},
                {"spider_name": "news_youth"},
                {"spider_name": "money_167"}, {"spider_name": "js_cri"}, {"spider_name": "ce_cn_cysc_sp"},
                {"spider_name": "money_168"}, {"spider_name": "money_169"}, {"spider_name": "money_170"},
                {"spider_name": "money_171"}, {"spider_name": "fj_cri"}, {"spider_name": "ce_cn_cysc_fdc"},
                {"spider_name": "hlj_cri"}, {"spider_name": "ce_cn_cysc_stwm"}, {"spider_name": "js_qq_dasuwang"},
                {"spider_name": "cq_cri"}, {"spider_name": "ce_cn_xwzx"}, {"spider_name": "gd_cri"},
                {"spider_name": "finance_ifeng1"}, {"spider_name": "sn_cri"}, {"spider_name": "finance_ifeng2"},
                {"spider_name": "hebei_cri"}, {"spider_name": "sd_cri"}, {"spider_name": "district_ce"},
                {"spider_name": "sc_cri"},
                {"spider_name": "ifeng"}, {"spider_name": "sc_cri2"}, {"spider_name": "finance_ce"},
                {"spider_name": "sh_cri"},
                {"spider_name": "ifeng1"}, {"spider_name": "health_ce"}, {"spider_name": "bj_cri"},
                {"spider_name": "cri"},
                {"spider_name": "xinwen_ubetween"}, {"spider_name": "js_ifeng"}, {"spider_name": "city_ce"},
                {"spider_name": "js_ifeng_nanjin"}, {"spider_name": "ce_cn"}, {"spider_name": "hb_youth"},
                {"spider_name": "js_ifeng_yangzhou"}, {"spider_name": "qh_youth"}, {"spider_name": "henan_youth"},
                {"spider_name": "js_ifeng_zhenjiang"}, {"spider_name": "js_ifeng_taizhou"},
                {"spider_name": "js_ifeng_suqian"},
                {"spider_name": "js_ifeng_suzhou"}, {"spider_name": "sn_youth"}, {"spider_name": "js_ifeng_nantong"},
                {"spider_name": "infzm1"}, {"spider_name": "sc_youth"}, {"spider_name": "js_ifeng_lianyungang"},
                {"spider_name": "he_youth"}, {"spider_name": "js_ifeng_huaian"}, {"spider_name": "df_youth"},
                {"spider_name": "ccfservice"}, {"spider_name": "cnstock"}, {"spider_name": "chinanews1"},
                {"spider_name": "cnstock1"}, {"spider_name": "chinanews_com_china"}, {"spider_name": "yinhang123_net"},
                {"spider_name": "chinanews_com_society"}, {"spider_name": "yndtjj"}, {"spider_name": "ah_chinanews"},
                {"spider_name": "farennews"}, {"spider_name": "weifang_dzwww"}, {"spider_name": "gd_sina1"},
                {"spider_name": "sohu2"}, {"spider_name": "bj_chinanews"}, {"spider_name": "business_sohu2"},
                {"spider_name": "cq_chinanews"}, {"spider_name": "gd.sina_1"}, {"spider_name": "news_sohu2"},
                {"spider_name": "tech_sina"}, {"spider_name": "tj_sina1"}, {"spider_name": "qingdaochina_org"},
                {"spider_name": "dezhoudaily"}, {"spider_name": "fj_chinanews"}, {"spider_name": "news_sohu1"},
                {"spider_name": "dezhoudaily2"}, {"spider_name": "police_news_sohu_com"},
                {"spider_name": "dezhoudaily3"},
                {"spider_name": "gd_chinanews"}, {"spider_name": "sohu_wang"}, {"spider_name": "tv_sohu1"},
                {"spider_name": "gx_chinanews"}, {"spider_name": "gz_chinanews"}, {"spider_name": "gs_chinanews"},
                {"spider_name": "heb_chinanews"}, {"spider_name": "ha_chinanews"}, {"spider_name": "hi_chinanews"},
                {"spider_name": "hi_chinanews1"}, {"spider_name": "hb_chinanews"}, {"spider_name": "hn_chinanews"},
                {"spider_name": "jx_chinanews"}, {"spider_name": "js_chinanews"}, {"spider_name": "jl_chinanews"},
                {"spider_name": "ln_chinanews"}, {"spider_name": "sd_chinanews"}, {"spider_name": "sx_chinanews"},
                {"spider_name": "sh_chinanews"}, {"spider_name": "sc_chinanews1"}, {"spider_name": "shx_chinanews"},
                {"spider_name": "xj_chinanews"}, {"spider_name": "zj_chinanews"}, {"spider_name": "cailianpress"},
                {"spider_name": "jjckb"}, {"spider_name": "quanjingwang"}, {"spider_name": "p5w"},
                {"spider_name": "cnfol"},
                {"spider_name": "cnfol1"}, {"spider_name": "cnfol2"}, {"spider_name": "qlwb_dzb"},
                {"spider_name": "cnfol3"},
                {"spider_name": "hexun"}, {"spider_name": "hexun1"}, {"spider_name": "eeo"}, {"spider_name": "zqrb"},
                {"spider_name": "yicai"}, {"spider_name": "xinhua08"}, {"spider_name": "bbtnews"},
                {"spider_name": "ftchinese"},
                {"spider_name": "finance_chinanews"}, {"spider_name": "chinanews4"},
                {"spider_name": "channel_chinanews"},
                {"spider_name": "chinanews_com1"}, {"spider_name": "xy178"}, {"spider_name": "military_china"},
                {"spider_name": "cxzg_china"}, {"spider_name": "jiangsu_china"}, {"spider_name": "food_china"},
                {"spider_name": "people_shanxi"}, {"spider_name": "union_china"}, {"spider_name": "china"},
                {"spider_name": "dudunews_net"}, {"spider_name": "cfi_net"}, {"spider_name": "cs"},
                {"spider_name": "cfi_net1"},
                {"spider_name": "jiemian"}, {"spider_name": "cfi_net2"}, {"spider_name": "caijing"},
                {"spider_name": "economy_caijing"}, {"spider_name": "economy_caijing1"},
                {"spider_name": "stock_caijing1"},
                {"spider_name": "fx168"}, {"spider_name": "stock_caijing2"}, {"spider_name": "finance_caijing"},
                {"spider_name": "fx168_huishi"}, {"spider_name": "industry_caijing"}, {"spider_name": "fx168_yanghang"},
                {"spider_name": "jrj"}, {"spider_name": "guancha"}, {"spider_name": "jrj1"}, {"spider_name": "jrj2"},
                {"spider_name": "jrj3"}, {"spider_name": "jrj4"}, {"spider_name": "jrj5"}, {"spider_name": "jrj6"},
                {"spider_name": "jrj7"}, {"spider_name": "jrj8"}, {"spider_name": "jrj9"}, {"spider_name": "jrj10"},
                {"spider_name": "jrj11"}, {"spider_name": "jrj12"}, {"spider_name": "jrj13"}, {"spider_name": "jrj14"},
                {"spider_name": "china1"}, {"spider_name": "china2"}, {"spider_name": "china3"},
                {"spider_name": "china4"},
                {"spider_name": "china5"}, {"spider_name": "china6"}, {"spider_name": "china7"},
                {"spider_name": "news_sohu3"},
                {"spider_name": "news_sohu4"}, {"spider_name": "news_sohu6"}, {"spider_name": "news_sohu7"},
                {"spider_name": "news_sohu8"}, {"spider_name": "police_news_sohu"}, {"spider_name": "sohu1"},
                {"spider_name": "sohu3"}, {"spider_name": "sohu4"}, {"spider_name": "business_sohu1"},
                {"spider_name": "business_sohu3"}, {"spider_name": "business_sohu4"}, {"spider_name": "society_sohu1"},
                {"spider_name": "ce"}, {"spider_name": "tcwmw"}, {"spider_name": "ce1"},
                {"spider_name": "fx168_yanwen"},
                {"spider_name": "v_ifeng"}, {"spider_name": "fx168_rmb"}, {"spider_name": "ce3"},
                {"spider_name": "jyxfj.jiangyan_gov"}, {"spider_name": "fx168_all"}, {"spider_name": "taicangdaily"},
                {"spider_name": "ce4"}, {"spider_name": "feng_ifeng"}, {"spider_name": "jingji21"},
                {"spider_name": "gov_ifeng"},
                {"spider_name": "nbd"}, {"spider_name": "district_ce1"}, {"spider_name": "travel_ifeng"},
                {"spider_name": "financeun"}, {"spider_name": "district_ce2"}, {"spider_name": "jymzj_jys_gov_cn"},
                {"spider_name": "js_ifeng1"}, {"spider_name": "jrh_financeun"}, {"spider_name": "finance_ce1"},
                {"spider_name": "suzhou"}, {"spider_name": "jywsjd_com_cn"}, {"spider_name": "eastmoney"},
                {"spider_name": "js_ifeng2"}, {"spider_name": "qq1"}, {"spider_name": "caifuhao_eastmoney"},
                {"spider_name": "js_feng_xuzhou"}, {"spider_name": "youth_jiangyan"}, {"spider_name": "finance_qq"},
                {"spider_name": "xuyi"}, {"spider_name": "js_ifeng_xuzhou"}, {"spider_name": "finance_qq1"},
                {"spider_name": "xinmin"}, {"spider_name": "jyghj_jiangyan"}, {"spider_name": "js_ifeng_changzhou"},
                {"spider_name": "js_ifeng3"}, {"spider_name": "finance_qq2"}, {"spider_name": "jysfy_chinacourt_org"},
                {"spider_name": "money163"}, {"spider_name": "finance_qq3"}, {"spider_name": "finance_qq4"},
                {"spider_name": "jys_gov_cn"}, {"spider_name": "xinhuanet1"}, {"spider_name": "news_169"},
                {"spider_name": "finance_qq5"}, {"spider_name": "ggshw_org"}, {"spider_name": "xinhuanet_fortune"},
                {"spider_name": "redcross_gaogang_gov_cn"}, {"spider_name": " js_ifeng_yancheng"}, {},
                {"spider_name": "news_qq1"},
                {"spider_name": "ln_ifeng"}, {"spider_name": "news_qq2"}, {"spider_name": "jl_ifeng"},
                {"spider_name": "xinhuanet_comments"}, {"spider_name": "news_cz001"}, {"spider_name": "news_qq3"},
                {"spider_name": "xinhuanet_money"}, {"spider_name": "ggfy_gov_cn"}, {"spider_name": "news_qq4"},
                {"spider_name": "hebei_ifeng"}, {"spider_name": "changzhou_gov"}, {"spider_name": "v_qq"},
                {"spider_name": "zgh_gaogang"}, {"spider_name": "new_qq"}, {"spider_name": "hn_ifeng"},
                {"spider_name": "xinhuanet_yuqing"}, {"spider_name": "ggrd_gaogang"}, {"spider_name": "hb_ifeng"},
                {"spider_name": "xinhuanet_video"}, {"spider_name": "cz_bendibao"}, {"spider_name": "gaogang_gov"},
                {"spider_name": "xinhuanet_silkroad"}, {"spider_name": "zhong5"}, {"spider_name": "hunan_ifeng"},
                {"spider_name": "banyuetan_org"}, {"spider_name": "xinhuanet_city"}, {"spider_name": "fy_tzhl"},
                {"spider_name": "xinhuanet_politics"}, {"spider_name": "sn_ifeng"}, {"spider_name": "wj001"},
                {"spider_name": "bjinnovate"}, {"spider_name": "yinhang_net"}, {"spider_name": "jx_ifeng1"},
                {"spider_name": "xnb_tzhl"}, {"spider_name": "twoeggz"}, {"spider_name": "hncyfw"},
                {"spider_name": "wj_gov"},
                {"spider_name": "renda_tzhl_gov"}, {"spider_name": "finance_people"}, {"spider_name": "hllz_gov"},
                {"spider_name": "sinmeng"}, {"spider_name": "industry_people"}, {"spider_name": "eyylt"},
                {"spider_name": "ah_ifeng1"}, {"spider_name": "jingji_cctv"}, {"spider_name": "tzhlbb"},
                {"spider_name": "tn_changzhou_gov"}, {"spider_name": "cq_ifeng"}, {"spider_name": "tw.tzhl"},
                {"spider_name": "suzhou_news_fang"}, {"spider_name": "hainan_ifeng"}, {"spider_name": "stcn"},
                {"spider_name": "gd_ifeng"}, {"spider_name": "suzhou_news_fang1"}, {"spider_name": "ncwlfy_chinacourt"},
                {"spider_name": "am1116"}, {"spider_name": "qd_ifeng"}, {"spider_name": "tzhlrc_com"},
                {"spider_name": "tzhl_gov"},
                {"spider_name": "nanchangwl"}, {"spider_name": "sz_sina"}, {"spider_name": "tzhl_CMS"},
                {"spider_name": "lgbj_taizhou"}, {"spider_name": "gs_csztv"}, {"spider_name": "wjj_taizhou"},
                {"spider_name": "nb_ifeng"}, {"spider_name": "cppcc_china"}, {"spider_name": "zj_ifeng"},
                {"spider_name": "js_sgcc"}, {"spider_name": "gs_ifeng"}, {"spider_name": "gs_csztv1"},
                {"spider_name": "csztv"},
                {"spider_name": "kjj_taizhou"}, {"spider_name": "hlj_ifeng"}, {"spider_name": "city_china"},
                {"spider_name": "edu_china"}, {"spider_name": "xwfbh_suzhou_gov"}, {"spider_name": "jstzdx_cn"},
                {"spider_name": "mytaizhou"}, {"spider_name": "health_china"}, {"spider_name": "finance_ifeng3"},
                {"spider_name": "tzdjw"}, {"spider_name": "news_2500sz"}, {"spider_name": "tjj_taizhou"},
                {"spider_name": "wl_nc"},
                {"spider_name": "tzcourt"}, {"spider_name": "jyj_taizhou"}, {"spider_name": "cztn_jsjc_gov"},
                {"spider_name": "caixin1"}, {"spider_name": "qyp"}, {"spider_name": "sz_tznews"},
                {"spider_name": "cailianpress1"},
                {"spider_name": "qshfy"}, {"spider_name": "cztn_jsjc_gov1"}, {"spider_name": "rsj_taizhou"},
                {"spider_name": "cailianpress2"}, {"spider_name": "qshlz"}, {"spider_name": "tzjob_com"},
                {"spider_name": "cztn_jsjc_gov2"}, {"spider_name": "taizhou_gov_cn"}, {"spider_name": "nanchangqsh"},
                {"spider_name": "cnfol4"}, {"spider_name": "cnfol5"}, {"spider_name": "fy_tzhl_gov_cn"},
                {"spider_name": "czjt_jsjc_gov_jintan"}, {"spider_name": "fund_cnfol"}, {"spider_name": "eco_cri"},
                {"spider_name": "jhzzb_gov_cn"}, {"spider_name": "xg_stock_cnfol"}, {"spider_name": "if_cri"},
                {"spider_name": "czjkq_jsjc_gov"}, {"spider_name": "jinhu_gov"}, {"spider_name": "czly_jsjc_gov"},
                {"spider_name": "cztmh_jsjc_gov"}, {"spider_name": "money_cri"}, {"spider_name": "bank_cnfol"},
                {"spider_name": "cj_crionline"}, {"spider_name": "jq_cri"}, {"spider_name": "news_cnfol"},
                {"spider_name": "county_cri"}, {"spider_name": "stock_cnfol"}, {"spider_name": "xuyi_gov"},
                {"spider_name": "bj_cri1"}, {"spider_name": "stock_cnfol2"}, {"spider_name": "rd_ianshui"},
                {"spider_name": "sh_cri1"}, {"spider_name": "mp_cnfol"}, {"spider_name": "p5w_net"},
                {"spider_name": "ncqsh"},
                {"spider_name": "jxjinxian"}, {"spider_name": "lsxw_net_cn"}, {"spider_name": "haotoutiao"},
                {"spider_name": "sc_cri1"}, {"spider_name": "ldxx_lianshui"}, {"spider_name": "jinxian"},
                {"spider_name": "ycwb_guangdong"}, {"spider_name": "sd_cri1"}, {"spider_name": "nc_jxnews"},
                {"spider_name": "lianshui_gov_cn"}, {"spider_name": "anyi"}, {"spider_name": "ycwb_huizhou"},
                {"spider_name": "wmw_hongze_gov_cn"}, {"spider_name": "jshzjjkfq_cn"}, {"spider_name": "nmg_chinanews"},
                {"spider_name": "qh_chinanews"}, {"spider_name": "hzjw_hongze_gov_cn"}, {"spider_name": "hzztb_cn"},
                {"spider_name": "hkcna_hk"}, {"spider_name": "yn_chinanews"}, {"spider_name": "news_10jqka"},
                {"spider_name": "jxwuyuan"}, {"spider_name": "zfw_hongze_gov_cn"}, {"spider_name": "zzb_hongze_gov_cn"},
                {"spider_name": "wyxfy"}, {"spider_name": "hzxw_net_cn"}, {"spider_name": "jxwy"},
                {"spider_name": "legaldaily2"},
                {"spider_name": "redian"}, {"spider_name": "legaldaily3"}, {"spider_name": "sryyfy_chinacourt"},
                {"spider_name": "jshzdj_gov_cn"}, {"spider_name": "toutiao"}, {"spider_name": "jxyy"},
                {"spider_name": "toutiao_image"}, {"spider_name": "poyangxian"}, {"spider_name": "master_10jqka"},
                {"spider_name": "222_184_84_82"}, {"spider_name": "poyang"}, {"spider_name": "hongze_gov_cn"},
                {"spider_name": "jxsr"}, {"spider_name": "zjg_js_cn"}, {"spider_name": "cnr"}, {"spider_name": "zgys"},
                {"spider_name": "zjgedu_cn"}, {"spider_name": "views_ce"}, {"spider_name": "ygxfy"},
                {"spider_name": "travel_ce"},
                {"spider_name": "zjgxw_com"}, {"spider_name": "cnr1"}, {"spider_name": "yugan_gov"},
                {"spider_name": "zjgxw_com_1"}, {"spider_name": "xinzhouqu"}, {"spider_name": "jxxz"},
                {"spider_name": "news_sipac"}, {"spider_name": "wannianxian"}, {"spider_name": "gzjd_sipac"},
                {"spider_name": "zgwn_gov"}, {"spider_name": "shangraoxian"}, {"spider_name": "srx"},
                {"spider_name": "sipac_gov_cn1"}, {"spider_name": "szyqfy_gov_cn"}, {"spider_name": "ysxww"},
                {"spider_name": "yanshanxian"}, {"spider_name": "chinanews_ga"}, {"spider_name": "chinanews_taiwan"},
                {"spider_name": "sd_youth"}, {"spider_name": "jxyanshan"}, {"spider_name": "chinanews_huaren"},
                {"spider_name": "hfzf"}, {"spider_name": "chinanews_shipin"}, {"spider_name": "guangfengxian"},
                {"spider_name": "dexingshi"}, {"spider_name": "cq_chinanews_shiping"}, {"spider_name": "jingdezhenzs"},
                {"spider_name": "jdzzsq"}, {"spider_name": "cmstop_zt_jsw"}, {"spider_name": "edu_youth"},
                {"spider_name": "ntjoy"}, {"spider_name": "j01_123"}, {"spider_name": "ntjoy1"},
                {"spider_name": "jxnf"},
                {"spider_name": "ntxww"}, {"spider_name": "jxncxfy"}, {"spider_name": "jxnc"},
                {"spider_name": "jxlcrd"},
                {"spider_name": "mp_sohu"}, {"spider_name": "club_china"}, {"spider_name": "zgfznews"},
                {"spider_name": "news_hytc_edu_cn"}, {"spider_name": "hywsjdw_com"}, {"spider_name": "club_china1"},
                {"spider_name": "gov_sohu"}, {"spider_name": "hahyfy_chinacourt_org"}, {"spider_name": "zfw_zghy"},
                {"spider_name": "dztv_tv"}, {"spider_name": "newshy_net"}, {"spider_name": "business_sohu5"},
                {"spider_name": "rd_zghy_gov_cn"}, {"spider_name": "zzb_zghy"}, {"spider_name": "j01_123_lc"},
                {"spider_name": "dztv_tv_news"}, {"spider_name": "qjpfy_gov_cn"}, {"spider_name": "j01_123_lcx"},
                {"spider_name": "j01_123_lx"}, {"spider_name": "zzb_haqp"}, {"spider_name": "j01_123_yz"},
                {"spider_name": "j01_123_yfx"}, {"spider_name": "finance_dztv_tv"}, {"spider_name": "jw_haqp"},
                {"spider_name": "j01_123_wzx"}, {"spider_name": "j01_123_tgx"}, {"spider_name": "city_sina"},
                {"spider_name": "haqp_gov_cn"}, {"spider_name": "j01_123_sgx"}, {"spider_name": "j01_123_jgx"},
                {"spider_name": "ettoday_net"}, {"spider_name": "j01_123_gas"}, {"spider_name": "j01_123_fxx"},
                {"spider_name": "fcwlwz"}, {"spider_name": "mop"}, {"spider_name": "haqp_gov_cn_1"},
                {"spider_name": "czzgh_org"},
                {"spider_name": "haqfy"}, {"spider_name": "jshaqnews_com"}, {"spider_name": "fcwlwz2"},
                {"spider_name": "news_163_1"}, {"spider_name": "wuhu_gov1"}, {"spider_name": "hefeifabu1"},
                {"spider_name": "hsnewsnet"}, {"spider_name": "hfxf_gov"}, {"spider_name": "kmsst"},
                {"spider_name": "ahhuangshan1"}, {"spider_name": "hfcz_gov"}, {"spider_name": "wewuhu"},
                {"spider_name": "chizhou_gov"}, {"spider_name": "huangshannews"}, {"spider_name": "hfcz_gov2"},
                {"spider_name": "wuhunews1"}, {"spider_name": "life_hefei_cc"}, {"spider_name": "xnpyw"},
                {"spider_name": "life_hefei_cc2"}, {"spider_name": "czwyz1"}, {"spider_name": "hf365"},
                {"spider_name": "chiznews"}, {"spider_name": "wehefei"}, {"spider_name": "ahbbtv1"},
                {"spider_name": "chuzhou1"},
                {"spider_name": "wehefei1"}, {"spider_name": "iluan1"}, {"spider_name": "bbnews"},
                {"spider_name": "massp"},
                {"spider_name": "luan163"}, {"spider_name": "wjol_net"}, {"spider_name": "xuanwww"},
                {"spider_name": "wanxinet1"},
                {"spider_name": "tl_gov"}, {"spider_name": "luan"}, {"spider_name": "news_newsxc"},
                {"spider_name": "tlnews"},
                {"spider_name": "news_newsxc_1"}, {"spider_name": "luaninfo"}, {"spider_name": "aqnews"},
                {"spider_name": "aqw_cc"}, {"spider_name": "anqing_gov"}, {"spider_name": "ahaq_wenming1"},
                {"spider_name": "aqzy_gov1"}, {"spider_name": "tengzhou"}, {"spider_name": "ahbanker"},
                {"spider_name": "mas_gov"},
                {"spider_name": "wjol_net1"}, {"spider_name": "jia365"}, {"spider_name": "jia_news"},
                {"spider_name": "home_jia"},
                {"spider_name": "money_jia"}, {"spider_name": "hbnews_net"}, {"spider_name": "bozhou"},
                {"spider_name": "luaninfo1"}, {"spider_name": "fynews"}, {"spider_name": "chinaso"},
                {"spider_name": "chinaso1"},
                {"spider_name": "yybnet"}, {"spider_name": "yybnet1"}, {"spider_name": "hnbynews.com"},
                {"spider_name": "ahcaijing"}, {"spider_name": "hngd"}, {"spider_name": "hf3651"},
                {"spider_name": "xinhua081"},
                {"spider_name": "xinjr"}, {"spider_name": "sme"}, {"spider_name": "ah_people"},
                {"spider_name": "huoqiuw"},
                {"spider_name": "fy169"}, {"spider_name": "bozhou2"}, {"spider_name": "chizhou"},
                {"spider_name": "xuancheng"},
                {"spider_name": "luan1"}, {"spider_name": "chuzhou2"}, {"spider_name": "ahsz"},
                {"spider_name": "jdzol3"},
                {"spider_name": "a453000"}, {"spider_name": "cngold"}, {"spider_name": "ahyouth"},
                {"spider_name": "huijindi"},
                {"spider_name": "ahxinwen"}, {"spider_name": "hefei123"}, {"spider_name": "mp_sohu1"},
                {"spider_name": "ah_xinhuanet"}, {"spider_name": "cnr2"}, {"spider_name": "ah_new"},
                {"spider_name": "money_1631"},
                {"spider_name": "toutiao1"}, {"spider_name": "jschina1"}]

urls = ["http://222.93.105.248:6800/schedule.json", "http://222.93.106.15:6800/schedule.json",
        "http://222.93.106.248:6800/schedule.json",
        "http://222.93.106.240:6800/schedule.json", "http://180.101.149.178:6800/schedule.json"]

def run ():
    cout = 0
    errorname = []
    for name_spider in spider_names:
        try:
            if 'spider_name' in name_spider.keys():
                uuid = uuid4().hex
                ip = random.choice(urls)
                data = {"project": "news_project",
                        "spider_type": "news",
                        "name_spider": name_spider['spider_name'],
                        "spider_jobid": uuid}
                txt = json.loads(requests.post(url=ip, data=data).content)
                txt['ip'] = ip
                # time.sleep(0.1)
                print(txt)
        except:
            cout += 1
            continue

    print(cout)

if __name__=='__main__':
    pass
    # run()
    # url = 'http://sync.yuwoyg.com:8086/api/web/manage/config/newsConfig/searchAll?columns=spider_name%2Ccrontab'
    # print(requests.get(url).content)
    # a = dict({"name_spider": "liwei"})
    # print('name_spider' in a.keys())
